services:
  php:
    build: ./php
    container_name: moodle_php
    restart: always
    volumes:
      - ./moodle/public_html:/var/www/html  # کدهای Moodle در اینجا قرار می‌گیرند
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - moodle-net

  nginx:
    image: nginx:latest
    container_name: moodle_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./moodle/public_html:/var/www/html  # کدهای Moodle در اینجا قرار می‌گیرند
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - moodle-net

  moodle:
    build:
      context: ./php  # دایرکتوری که Dockerfile در آن قرار دارد
      dockerfile: Dockerfile  # نام فایل Dockerfile
    container_name: moodle_app
    restart: always
    #depends_on:
    #  - mariadb
    environment:
      MOODLE_DBTYPE: mariadb
      MOODLE_DBHOST: moodle_db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle_user
      MOODLE_DBPASSWORD: moodle_password
    volumes:
      - ./moodle/public_html:/var/www/html  # کدهای Moodle در اینجا قرار می‌گیرند
      - ./moodle/moodle_data:/var/www/moodledata  # داده‌های Moodle در اینجا ذخیره می‌شود
    user: "www-data"
    networks:
      - moodle-net

volumes:
  moodle_db_data:
  moodle_data:

networks:
  moodle-net:
    external: true