services:
  mariadb:
    image: mariadb:10.5
    container_name: moodle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_password
    volumes:
      - moodle_db_data:/var/lib/mysql
    networks:
      - moodle_network

  php:
    build: ./php
    container_name: moodle_php
    restart: always
    volumes:
     #- ../moodle:/var/www/html
      - ./moodle:/var/www/html  # مسیر اصلاح شد
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - moodle_network

  nginx:
    image: nginx:latest
    container_name: moodle_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      #- ../moodle:/var/www/html
      - ./moodle:/var/www/html  # مسیر اصلاح شد
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - moodle_network

  moodle:
    build: ../moodle
    container_name: moodle_app
    restart: always
    depends_on:
      - mariadb
    environment:
      MOODLE_DBTYPE: mariadb
      MOODLE_DBHOST: moodle_db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle_user
      MOODLE_DBPASSWORD: moodle_password
    volumes:
      - ../moodle:/var/www/html
    networks:
      - moodle_network

volumes:
  moodle_db_data:
  moodle_data:

networks:
  moodle_network: