version: '3.8'

services:
  php:
    build: ./php
    container_name: moodle_php
    restart: always
    volumes:
      - ./moodle/public_html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    container_name: moodle_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./moodle/public_html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  moodle:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: moodle_app
    restart: always
    depends_on:
      - php
    environment:
      MOODLE_DBTYPE: mariadb
      MOODLE_DBHOST: moodle_db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle_user
      MOODLE_DBPASSWORD: moodle_password
    volumes:
      - ./moodle/public_html:/var/www/html
      - ./moodle/moodle_data:/var/www/moodledata
    user: "www-data"
